### ISSUE TITLE
Typo on Ansible-galaxy readme

### ISSUE THREAD

**Issue by csuka** [Keeper-Security/secrets-manager#222]
On the [ansible-galaxy for keeper](https://galaxy.ansible.com/keepersecurity/keeper_secrets_manager), it states:

```yaml
keepersecrity.keeper_secrets_manager
```

This is incorrect, it should be:

```yaml
keepersecurity.keeper_secrets_manager
```

**Comment by maksimu** [comment]
@csuka Thank you for reporting this issue to us. We will create a new release soon with the fix.
