### ISSUE TITLE
JavaScript SDK function `loadJsonConfig` is undocumented

### ISSUE THREAD

**Issue by Kytech** [Keeper-Security/secrets-manager#234]
The `loadJsonConfig` function is not documented in the documentation for the KSM JavaScript SDK. This function is exported and works as expected, though the only way one would know about what it does is to dive in to the JavaScript SDK codebase.

**Comment by Kytech** [comment]
For additional context, I discovered the function out of a necessity for working around another issue I detail in #233, though this particular function for creating the `KeyValueStorage` could be useful in other scenarios.

**Comment by maksimu** [comment]
@Kytech thank you for your feedback!  We will be adding more documentation to our [documentation page](https://docs.keeper.io/secrets-manager/secrets-manager/developer-sdk-library) in the near future, including how `loadJsonConfig` function works.

**Comment by maksimu** [comment]
Just wanted to let you know that you were using `loadJsonConfig` in our GitHub Actions integration. You can see the code [HERE](https://github.com/Keeper-Security/ksm-action/blob/master/src/main.ts#L59)
