### ISSUE TITLE
Make KSM cli binary compatible with Alpine

### ISSUE THREAD

**Issue by jgiovaresco** [Keeper-Security/secrets-manager#239]
It seems that the Linux binary is not compatible with Alpine Linux. We tried to run it in an Alpine-based container and we have

```
/bin/sh: ksm: not found
```

You can use the following Dockerfile as example:

```
FROM alpine:3.15

ENV OS=linux
ENV VERSION=1.0.8
ENV ARCHIVE_NAME=keeper-secrets-manager-cli-$OS-$VERSION
ENV LINK_TAR=https://github.com/Keeper-Security/secrets-manager/releases/download/ksm-cli-$VERSION/$ARCHIVE_NAME.tar.gz

WORKDIR /tmp

RUN apk add --no-cache curl
RUN curl -fsSL "${LINK_TAR}" | $SUDO tar -xz;

RUN ls -al
RUN ksm
```

The only way we found to run KSM cli on Alpine is to install it using PIP.

To give you some context, we wrote a small [CircleCI orb](https://github.com/gravitee-io/keeper-circleci-orb) to use KSM in our pipelines to ease our migration from SecretHub. 
We have a command `env-export` which is used to create an environment variable with a secret. This command requires `ksm` to be installed. On any other Linux distribution, the installation from the binary is quick. However, on Alpine-based, this installation step takes roughly 1min which could make our pipeline longer.

**Comment by jsupun** [comment]
The KSM CLI is compiled with **GLIBC**, which has been replaced by **MUSL** in Alpine. This seems to be a common problem with running binaries within Alpine.

Until we release a binary version for Alpine linux, you can always try to install **GLIBC** into the docker image. 

An attempt to use the a compatibility layer will still not work.

```
/ # ./ksm
sh: ./ksm: not found
/ # apk add gcompat
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/3) Installing musl-obstack (1.2.2-r0)
(2/3) Installing libucontext (1.1-r0)
(3/3) Installing gcompat (1.0.0-r4)
OK: 6 MiB in 17 packages
/ # ./ksm
[20] Error loading Python lib '/tmp/_MEInKJhHK/libpython3.6m.so.1.0': dlopen: Error relocating /tmp/_MEInKJhHK/libpython3.6m.so.1.0: __wcscat_chk: symbol not found
```

https://github.com/jeanblanchard/docker-alpine-glibc/blob/main/Dockerfile will get you closer, however there is a problem with locale. Even installing the glibc-i18n.apk from their release doesn't help. And this solution still needs `gcompat` installed, which will complain about "ib/ld-linux-x86-64.so.2 " being owned by "glibc-*" during the package install.

ksm will run, but it can't find any locale information, even if set the LANG and LC_* variables.

```
/ # ./ksm
ksm had a problem: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

Additional information: on this system no suitable UTF-8 locales were discovered. This most likely requires resolving by reconfiguring the locale system.

Click discovered that you exported a UTF-8 locale but the locale system could not pick up from it because it does not exist. The exported locale is 'C.UTF-8' but it is not supported.
```

**Comment by jsupun** [comment]
I've added a binary for Alpine called **keeper-secrets-manager-cli-alpine-linux-1.0.8.tar.gz**, https://github.com/Keeper-Security/secrets-manager/releases/download/ksm-cli-1.0.8/keeper-secrets-manager-cli-alpine-linux-1.0.8.tar.gz. Give that a try.

`ksm` should use the **musl** library instead **libc**.

```
/home/me # ldd ksm
	/lib/ld-musl-x86_64.so.1 (0x7fbcfe1b3000)
	libz.so.1 => /lib/libz.so.1 (0x7fbcfe176000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fbcfe1b3000)
```

**Comment by jgiovaresco** [comment]
Thanks @jsupun the binary works well 🙌
