### ISSUE TITLE
keeper.ini created when using KSM_CONFIG

### ISSUE THREAD

**Issue by jgiovaresco** [Keeper-Security/secrets-manager#246]
We initialize KSM cli using an environment KSM_CONFIG.

When we use any ksm command, the first time it will generate a `keeper.ini` file in the current directory.

I've noticed we can set `KSM_INI_DIR` to define where the file is stored. Even with this var defined, KSM will create a `keeper.ini` file in the current directory.

Would it be possible to prevent this file creation if the `KSM_INI_DIR` already contains a valid config?

**Comment by jsupun** [comment]
I can put it down for a "feature". Is this causing problem with you or can you just delete the keeper.ini when done?

**Comment by jgiovaresco** [comment]
I've implemented a workaround in CircleCI orb to run keeper-related commands in another directory. So for now, it's OK ;)
But it is uncommon behavior for me, it could be an improvement. I've struggled a bit with the documentation thinking I was doing something wrong 🙈

**Comment by jsupun** [comment]
This now exists in 1.0.10
