### ISSUE TITLE
Unable to find type [SecretManagement.Keeper.Client].

### ISSUE THREAD

**Issue by ppibeauty** [Keeper-Security/secrets-manager#263]
I believe there is an issue with the windows powershell version (as opposed to PowerShell Core) of this module.  I am working with a fresh install of server 2019 and going through setup of the module.  This is what I am seeing:

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> Set-PSRepository psgallery -InstallationPolicy Trusted
PS C:\Windows\system32> Install-Module -Name Microsoft.PowerShell.SecretManagement
PS C:\Windows\system32> Install-Module -Name SecretManagement.Keeper -RequiredVersion 16.0.4
PS C:\Windows\system32> Install-Module -Name Microsoft.Powershell.SecretStore
PS C:\Windows\system32> Register-SecretVault -Name LocalStore -ModuleName Microsoft.Powershell.SecretStore
PS C:\Windows\system32> register-KeeperVault -Name Keeper -LocalVaultName LocalStore -OneTimeToken *******
Storing Keeper Vault config KeeperVault.Keeper in Microsoft.Powershell.SecretStore Vault named LocalStore
Unable to find type [SecretManagement.Keeper.Client].
At C:\Program Files\WindowsPowerShell\Modules\SecretManagement.Keeper\16.0.4\SecretManagement.Keeper.psm1:29 char:13
+   $result = [SecretManagement.Keeper.Client]::GetVaultConfig($OneTime ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SecretManagement.Keeper.Client:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS C:\Windows\system32> get-host
Name             : ConsoleHost
Version          : 5.1.14393.4583
InstanceId       : ****
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by maksimu** [comment]
Hello @ppibeauty 
It appears that the Powershell is not able to locate `SecretsManager.dll` file. Can you confirm that you have a `SecretsManager.dll` on the same level as `.psd1` files in the module where you installed `SecretManagement.Keeper` module.

**Comment by maksimu** [comment]
you should see file structure like this:

![image](https://user-images.githubusercontent.com/187306/164084969-948c812b-261a-4bf7-8e1c-d3ee1de5bfcf.png)

https://www.powershellgallery.com/packages/SecretManagement.Keeper/16.2.1

**Comment by ppibeauty** [comment]
Yes I can confirm the file layout is the same:

![image](https://user-images.githubusercontent.com/66749083/164313722-d637d0ed-b758-44b4-a251-20b6c5e78c57.png)

**Comment by maksimu** [comment]
Can you try to remove all SecretManagement.Keeper modules and Reregister/Reset Secret Store, as you might have two versions installed or something in that nature.

Also, try to install latest Powershell, perhaps that will resolve the issue? Keep us posted.

**Comment by maksimu** [comment]
Closing inactive thread.

**Comment by ppibeauty** [comment]
Yes I can confirm the file layout is the same:
***@***.***
