### ISSUE TITLE
Strategy for storing secrets for multiple deployments of the same product

### ISSUE THREAD

**Issue by iamFIREcracker** [Keeper-Security/secrets-manager#280]
Within our organization, we are experimenting with using Keeper in our CI/CD pipeline, and we were reasoning about a solution for storing and accessing secrets for different deployments of the same product (e.g. production, staging, integration).  We initially thought about using nested directories as shown below:

```
our-app               (shared folder)
`-- production        (folder)
|   `-- REDIS_AUTH    (secret)
|   `-- DATABASE_URL  (secret)
`-- staging           (folder)
|   `-- REDIS_AUTH    (secret)
|   `-- DATABASE_URL  (secret)
```

And since the deployment environment is known by the time we need to the vault from our CI/CD platform (i.e. GitLab sets the `CI_ENVIRONMENT_NAME` environment variable with information about the target environemnt), we thought we could easily access secrets with a notation like: `file:///$CI_ENVIRONMENT_NAME/REDIS_AUTH`; however, Keeper Notation does not seem to support accessing records by their names / paths relative to the application directory, so we are kind of stuck, wondering if there wasn't a better way to deal with this.

Of course we could have each environment use different Keeper record IDs:

```
$ cat .env.production
REDIS_AUTH=keeper://KEEPER_ID_1/field/password

$ cat .env.staging
REDIS_AUTH=keeper://KEEPER_ID_2/field/password
```

And then source these files before before calling `ksm exec --`:

```
$ dotenv -f .env.$CI_ENVIRONMENT_NAME export
# This loads/exports from the Right .env file

$ ksm exec -- terraform ...
```

This works, but it requires us to copy/paste dozens of Keeper IDs, and we were hoping for something a bit less error prone than that.  What other alternatives do we have?  Would it make sense to store these .env files, with the actual secrets and not the Keeper notation, directly inside the vault?  This way one would simply need to deal with two IDs (or three, or as many as they have environments to deploy to) and at deploy time, they would only have to read the current environment file from the vault, source/re-export it, and move on with the deployment steps.

I am sure our team is not the first one having to implement this, so please let us know if you thought there were better ways to deal with this.

Thanks,
M.

**Comment by maksimu** [comment]
Hello @iamFIREcracker 
We have actually in process of finalizing functionality on the SDK level to get record(s) by title. You can actually see the changes in [THIS](https://github.com/Keeper-Security/secrets-manager/pull/276) PR. We are hoping to release this feature sometimes this week and then propagate this into the upstream integrations.
