### ISSUE TITLE
Windows defender claims latest version has a virus?

### ISSUE THREAD

**Issue by mickem** [Keeper-Security/secrets-manager#302]
Tried to download the latest client ([vault-plugin-secrets-ksm_1.0.2_windows_amd64.zip](https://github.com/Keeper-Security/secrets-manager/releases/download/vault-plugin-secrets-ksm%2Fv1.0.2/vault-plugin-secrets-ksm_1.0.2_windows_amd64.zip)) for windows but get this instead:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1434697/173344511-13ab9d3b-55f8-4c31-bf99-5964545d6386.png">

Sorry for the Swedish but it says there is a trojan called `Win32/Wacatac.B!ml` in the zip.

// Michael Medin

**Comment by maksimu** [comment]
Hello @mickem 
We have checked the file and we were not able to reproduce this on our machines as well as on few VMs in the cloud.
The next release of the Windows binary will be a signed binary. Also to make sure that the file is in tact you can just check checksum of the file that is located in the `vault-plugin-secrets-ksm_1.0.2_SHA256SUMS` file. 

Here are the checksums for both of the Windows files in the 1.0.2 release.

- `9209a4851b3230a4966825caaae7524aff7c27dbb95ebfa060e55fcbb96990dc`  vault-plugin-secrets-ksm_1.0.2_windows_386.zip
- `a7bf4ce6bf5a14475309c84d3dc24f72798467beffdfa3cb45d3303d2ac3f9cd`  vault-plugin-secrets-ksm_1.0.2_windows_amd64.zip

**Comment by maksimu** [comment]
@mickem we have released new Windows binaries that are signed. I hope this will help us to prevent false positives
