### ISSUE TITLE
`ksm profile init --token ...` produces a world readable `keeper.ini`

### ISSUE THREAD

**Issue by odormond** [Keeper-Security/secrets-manager#320]
Running `ksm profile init --token ...` produces a world readable `keeper.ini` in the current directory.

As stated in your own documentation (https://docs.keeper.io/secrets-manager/secrets-manager/about/security-encryption-model#client-device-configuration-file)

> This file should be protected on your local filesystem. It contains keys can authenticate with the Keeper API and decrypt secrets that have been explicitly associated with the Application and Client Device.

Tested with:
```
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

$ ksm version
Python Version: 3.10.4
Python Install: /usr/bin/python3
CLI Version: 1.0.14
CLI Install: /home/odormond/.local/lib/python3.10/site-packages/keeper_secrets_manager_cli
SDK Version: 16.3.4
SDK Install: /home/odormond/.local/lib/python3.10/site-packages/keeper_secrets_manager_core
Config file: /home/odormond/keeper.ini

$ ls -l keeper.ini
-rw-rw-r--  1 odormond odormond       645 Jul 15 09:32  keeper.ini
```

The `keeper.ini` should be created with an explicit mode of 0600 instead.

**Comment by jsupun** [comment]
Thanks for the feedback. We'll change the mode to 0600 after creation.
