### ISSUE TITLE
Unable to use python ksm cli tool if keeper record id starts with '-'

### ISSUE THREAD

**Issue by brandocomando** [Keeper-Security/secrets-manager#367]
getting an error trying to use ksm cli tool with a record who's UUID starts with -

```
 ksm secret notation '-iT4kWE2ZAkdHLqVlCfoWQ/field/Test'
Usage: ksm secret notation [OPTIONS] TEXT
Try 'ksm secret notation --help' for help.

Error: no such option: -i
```

I've tried single and double quotes around the UUID, as well as escaping the - with \

Anyone run into this issue before? 

I've noticed the same with ksm secret get UUID, but this can be avoided by using the -u option, but there is not an equivalent for ksm sync, or ksm secret notation.

**Comment by brandocomando** [comment]
FYI version info:
Python Version: 3.10.4
Python Install: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
CLI Version: 1.0.14
CLI Install: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keeper_secrets_manager_cli
SDK Version: 16.3.2
SDK Install: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keeper_secrets_manager_core
Config file: keeper.ini
Version 16.3.5 is available for the SDK

**Comment by jsupun** [comment]
Yeah, it thinks the "-" is indicating that the value is a parameters flag.

Either what @maksimu said, or prepend a "keeper://" for notation.

`ksm secret notation "keeper://-iT4kWE2ZAkdHLqVlCfoWQ/field/Test"`

**Comment by brandocomando** [comment]
Cool thanks for the quick response. Looks lke the "keeper://" format works for me.
