### ISSUE TITLE
ansible integration error

### ISSUE THREAD

**Issue by ppodevlab** [Keeper-Security/secrets-manager#439]
Hi guys, i'm trying to test the ansible integration but i'm getting an error.

Code:
```
- name: test
  hosts: localhost
  collections:
   - keepersecurity.keeper_secrets_manager
  tasks: 
  - name: Get value
    debug:
      msg: "{{ lookup('keepersecurity.keeper_secrets_manager.keeper', uid='myId', field='login') }}"
```
Error: 
```
ImportError: cannot import name 'KeeperAnsible' from 'ansible_collections.keepersecurity.keeper_secrets_manager.plugins.common.keeper_secrets_manager_ansible' (/Users/user/.ansible/collections/ansible_collections/keepersecurity/keeper_secrets_manager/plugins/common/keeper_secrets_manager_ansible/__synthetic__)
```

Ansible config: 
```
❯ ansible --version
ansible 2.9.18
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/.asdf/installs/python/3.8.16/lib/python3.8/site-packages/ansible
  executable location = /Users/user/.asdf/installs/python/3.8.16/bin/ansible
  python version = 3.8.16 (default, Mar 13 2023, 22:19:52) [Clang 14.0.0 (clang-1400.0.29.202)]
```
Am i missing anything?

**Comment by jwalstra-keeper** [comment]
It looks like it's the version of Ansible. I was able to reproduce this the same version of ansible and Python. I updated my version to 2.10.7, the last of the 2.x versions, and it did work.


**Ansible 2.9.18**
```shell
(venv) ~/testing/ansible/issue_439(:|✔) % ansible-playbook playbooks/keeper_test.yml

PLAY [Keeper Test] ******************************************************************************************************************************************************************************

TASK [Keeper Info] ******************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'KeeperAnsible' from 'ansible_collections.keepersecurity.keeper_secrets_manager.plugins.common.keeper_secrets_manager_ansible' (/Users/jwalstra/.ansible/collections/ansible_collections/keepersecurity/keeper_secrets_manager/plugins/common/keeper_secrets_manager_ansible/__synthetic__)
fatal: [10.0.1.18]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP **************************************************************************************************************************************************************************************
10.0.1.18                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

(venv) ~/testing/ansible/issue_439(:|✔) % ansible --version
ansible 2.9.18
  config file = /Users/XXXX/testing/ansible/issue_439/ansible.cfg
  configured module search path = ['/Users/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXXX/testing/ansible/issue_439/venv/lib/python3.8/site-packages/ansible
  executable location = /Users/XXXX/testing/ansible/issue_439/venv/bin/ansible
  python version = 3.8.16 (default, Mar 22 2023, 10:36:18) [Clang 14.0.0 (clang-1400.0.29.202)]
```

**Ansible 2.10.17**
```shell
(venv) ~/testing/ansible/issue_439(:|✔) % ansible --version
ansible 2.10.17
  config file = /Users/jwalstra/testing/ansible/issue_439/ansible.cfg
  configured module search path = ['/Users/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXXX/testing/ansible/issue_439/venv/lib/python3.8/site-packages/ansible
  executable location = /Users/XXXX/testing/ansible/issue_439/venv/bin/ansible
  python version = 3.8.16 (default, Mar 22 2023, 10:36:18) [Clang 14.0.0 (clang-1400.0.29.202)]

(venv) ~/testing/ansible/issue_439(:|✔) % ansible-playbook playbooks/keeper_test.yml

PLAY [Keeper Test] **************************************************************************************************************************************************

TASK [Keeper Info] **************************************************************************************************************************************************
ok: [10.0.1.18]

TASK [Make Test Directory] ******************************************************************************************************************************************
ok: [10.0.1.18] => (item=.ssh)

TASK [Get timestamp from the system] ********************************************************************************************************************************
changed: [10.0.1.18]

TASK [Generate a password] ******************************************************************************************************************************************
ok: [10.0.1.18]

TASK [Display Long Pass] ********************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "Long password #^fkIQ;@]QT2s97Dii]!Ugi[,6Jl(;yv97bNSH8bD{;;ri98=[z}cyHDbQ\"48q7TOu69]4p?8U8%%kWz194!X9l9aLY<OXS2!5kTk;@0rL78>r9<37G)8<VC2zHdq?KO"
}

TASK [Generate all digit password, No 4s] ***************************************************************************************************************************
ok: [10.0.1.18]

TASK [Display Digit Pass, no 4s] ************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "Digit password 7132780393336509103806570807685530311937033761783787613099892525"
}

TASK [Create A Record] **********************************************************************************************************************************************
ok: [10.0.1.18]

TASK [New Record UID] ***********************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "New record uid is 0SXE5PpgAaEaqyz5SGkLhA"
}

TASK [Create A Custom Record] ***************************************************************************************************************************************
ok: [10.0.1.18]

TASK [New Record UID (Azure)] ***************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "New record uid is XaPbGBJyl7HFzHnzkpSa0w"
}

TASK [Copy Test SSH Keys] *******************************************************************************************************************************************
ok: [10.0.1.18] => (item={'notation_key': 'privateKey', 'filename': 'id_rsa'})
ok: [10.0.1.18] => (item={'notation_key': 'publicKey', 'filename': 'id_rsa.pub'})

TASK [Get Login] ****************************************************************************************************************************************************
ok: [10.0.1.18]

TASK [Get Phone Number] *********************************************************************************************************************************************
ok: [10.0.1.18]

TASK [Get Phone Number via Notation] ********************************************************************************************************************************
ok: [10.0.1.18]

TASK [Get Time] *****************************************************************************************************************************************************
changed: [10.0.1.18]

TASK [Set Value] ****************************************************************************************************************************************************
ok: [10.0.1.18]

TASK [lookup uid] ***************************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "my text {'number': '(262) 353-1425', 'type': 'Work', 'ext': '6666'}"
}

TASK [lookup all] ***************************************************************************************************************************************************
ok: [10.0.1.18]

TASK [lookup first] *************************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "my text {'number': '(262) 353-1425', 'type': 'Work', 'ext': '6666'}"
}

TASK [lookup number] ************************************************************************************************************************************************
ok: [10.0.1.18] => {
    "msg": "my text (262) 353-1425"
}

TASK [Clean Up] *****************************************************************************************************************************************************
ok: [10.0.1.18]

PLAY RECAP **********************************************************************************************************************************************************
10.0.1.18                  : ok=22   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ppodevlab** [comment]
> It looks like it's the version of Ansible. I was able to reproduce this the same version of ansible and Python. I updated my version to 2.10.7, the last of the 2.x versions, and it did work.
> 
> **Ansible 2.9.18**
> 
> ```shell
> (venv) ~/testing/ansible/issue_439(:|✔) % ansible-playbook playbooks/keeper_test.yml
> 
> PLAY [Keeper Test] ******************************************************************************************************************************************************************************
> 
> TASK [Keeper Info] ******************************************************************************************************************************************************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'KeeperAnsible' from 'ansible_collections.keepersecurity.keeper_secrets_manager.plugins.common.keeper_secrets_manager_ansible' (/Users/jwalstra/.ansible/collections/ansible_collections/keepersecurity/keeper_secrets_manager/plugins/common/keeper_secrets_manager_ansible/__synthetic__)
> fatal: [10.0.1.18]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
> 
> PLAY RECAP **************************************************************************************************************************************************************************************
> 10.0.1.18                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
> 
> (venv) ~/testing/ansible/issue_439(:|✔) % ansible --version
> ansible 2.9.18
>   config file = /Users/XXXX/testing/ansible/issue_439/ansible.cfg
>   configured module search path = ['/Users/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /Users/XXXX/testing/ansible/issue_439/venv/lib/python3.8/site-packages/ansible
>   executable location = /Users/XXXX/testing/ansible/issue_439/venv/bin/ansible
>   python version = 3.8.16 (default, Mar 22 2023, 10:36:18) [Clang 14.0.0 (clang-1400.0.29.202)]
> ```
> 
> **Ansible 2.10.17**
> 
> ```shell
> (venv) ~/testing/ansible/issue_439(:|✔) % ansible --version
> ansible 2.10.17
>   config file = /Users/jwalstra/testing/ansible/issue_439/ansible.cfg
>   configured module search path = ['/Users/XXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /Users/XXXX/testing/ansible/issue_439/venv/lib/python3.8/site-packages/ansible
>   executable location = /Users/XXXX/testing/ansible/issue_439/venv/bin/ansible
>   python version = 3.8.16 (default, Mar 22 2023, 10:36:18) [Clang 14.0.0 (clang-1400.0.29.202)]
> 
> (venv) ~/testing/ansible/issue_439(:|✔) % ansible-playbook playbooks/keeper_test.yml
> 
> PLAY [Keeper Test] **************************************************************************************************************************************************
> 
> TASK [Keeper Info] **************************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Make Test Directory] ******************************************************************************************************************************************
> ok: [10.0.1.18] => (item=.ssh)
> 
> TASK [Get timestamp from the system] ********************************************************************************************************************************
> changed: [10.0.1.18]
> 
> TASK [Generate a password] ******************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Display Long Pass] ********************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "Long password #^fkIQ;@]QT2s97Dii]!Ugi[,6Jl(;yv97bNSH8bD{;;ri98=[z}cyHDbQ\"48q7TOu69]4p?8U8%%kWz194!X9l9aLY<OXS2!5kTk;@0rL78>r9<37G)8<VC2zHdq?KO"
> }
> 
> TASK [Generate all digit password, No 4s] ***************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Display Digit Pass, no 4s] ************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "Digit password 7132780393336509103806570807685530311937033761783787613099892525"
> }
> 
> TASK [Create A Record] **********************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [New Record UID] ***********************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "New record uid is 0SXE5PpgAaEaqyz5SGkLhA"
> }
> 
> TASK [Create A Custom Record] ***************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [New Record UID (Azure)] ***************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "New record uid is XaPbGBJyl7HFzHnzkpSa0w"
> }
> 
> TASK [Copy Test SSH Keys] *******************************************************************************************************************************************
> ok: [10.0.1.18] => (item={'notation_key': 'privateKey', 'filename': 'id_rsa'})
> ok: [10.0.1.18] => (item={'notation_key': 'publicKey', 'filename': 'id_rsa.pub'})
> 
> TASK [Get Login] ****************************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Get Phone Number] *********************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Get Phone Number via Notation] ********************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [Get Time] *****************************************************************************************************************************************************
> changed: [10.0.1.18]
> 
> TASK [Set Value] ****************************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [lookup uid] ***************************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "my text {'number': '(XXX) XXX-XXXX', 'type': 'Work', 'ext': '6666'}"
> }
> 
> TASK [lookup all] ***************************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> TASK [lookup first] *************************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "my text {'number': '(XXX) XXX-XXXX', 'type': 'Work', 'ext': '6666'}"
> }
> 
> TASK [lookup number] ************************************************************************************************************************************************
> ok: [10.0.1.18] => {
>     "msg": "my text (XXX) XXX-XXXX"
> }
> 
> TASK [Clean Up] *****************************************************************************************************************************************************
> ok: [10.0.1.18]
> 
> PLAY RECAP **********************************************************************************************************************************************************
> 10.0.1.18                  : ok=22   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
> ```

Thanks for testing! Too bad. I can not use it in this project till we update some dependencies.

Will close it for now
