### ISSUE TITLE
Credentials Stored in Plaintext in Memory

### ISSUE THREAD

**Issue by H4rk3nz0** [Keeper-Security/secrets-manager#486]
Hi, 

I noticed that, even following session time-out or record deletion, keeper stores records as plaintext JSON in memory. So long as a user initiated signout or app restart is not performed one can extract all credentials from memory in plain text. This includes the browser extensions.

**Comment by H4rk3nz0** [comment]
Hi Max,

Apologies for the confusion and mix-up regarding the SDK/Secrets Manager and normal Desktop and Browser Extension for the password manager offerings.

Yes, the issue I am attempting to raise is related to the ease by which one can isolate and extract plain text records from the Desktop and Browser Password manager solutions offered by Keeper. As it is an electron application and V8 memory management is in use the desktop app almost always allocates pointers to stored strings in running memory at regions aligning to `0x05fff0010` in increments of 0x10 bytes (eg: `0x05fff0020, 0x05fff0030, ... 0x05fff0ff0`) with the next region being an increment of 0x10000000 (eg: `0x06fff0010 -> 0x06fff0ff0`) and so on. 

By iterating over a relatively small set of memory spaces up till 0x2ffff0ff0 it is possible to pull pointers to all stored records in plain text as this appears to be the default means of storage in the Desktop program's memory.

The desktop app also always stores the entered master login key in plain text appended with `data_key<master-password>`. These credentials and records persist in memory after a session timeout and record is deleted. So long as a user does not initiate a manual logout or shut down keeper entirely, all their credentials are freely available for theft from memory by potential adversaries.

As for the browser extension - i have yet to figure out the memory mapping but the extension stores the same credentials in JSON plain text in the browser memory.

I have attempted to search for a means of reporting this but Keepers vulnerability disclosure appears to indicate reports for issues that assume compromise of a user endpoint or operating system are not in scope or valid for submission. Any ideas or assistance is appreciated. This is a very serious issue in cryptographic implementation and secure management of memory.

If you need more information or proof please let me know.

Regards,
Chris

**Comment by H4rk3nz0** [comment]
Hi @craiglurey,

From my testing I was able to still extract credentials after an autologout/session timeout as it did not appear to appropriately clear memory until a manual restart or logout was initiated by the user. I will retest this and confirm to be sure. I'll reach out in the coming days regarding the issues I've identified, thanks for the assistance.

**Comment by craiglurey** [comment]
Ok, if that's reproducible then you can definitely submit a Bugcrowd report and we'll look at it right away. Here's the URL: https://bugcrowd.com/keepersecurity
