### ISSUE TITLE
Cyclical dependency in Python SDK

### ISSUE THREAD

**Issue by allanadair** [Keeper-Security/secrets-manager#488]
At the current release, 16.5.4, there is a cyclical dependency. keeper-secrets-manager-core depends on keeper-secrets-manager-helper, which in turn depends on keeper-secrets-manager-core, making this package impossible to build in some environments.

**Comment by allanadair** [comment]
Is there any possibility that these two packages, "core" and "helper" could instead be two modules within one parent package?

The secrets-manager/sdk/python folder is a Python module containing an __init__.py and un-importable packages ("core, "helper", and "storage") and it hints that perhaps a developer got mixed up with the differences between modules and packages. That might not be the case! But it does present a problem when two packages depend on each other. Dependency revolvers have a hard time dealing with this and it is problematic for package maintainers. Myself included.

If instead the "secrets-manager/sdk/python" folder were made into a parent package with "core", "helper", and "storage" modules, some pressure would be eased. I would be happy to submit a pull request with a solution if this is desirable!

**Comment by allanadair** [comment]
Sure, I hope this comment helps. Here's the directory structure that I am referring to. Today's master branch:

```shell
$ tree -L 2 secrets-manager/sdk/python/
secrets-manager/sdk/python/
├── core
│   ├── keeper_secrets_manager_core
│   ├── LICENSE.txt
│   ├── README.md
│   ├── requirements.txt
│   ├── setup.cfg
│   ├── setup.py
│   └── tests
├── helper
│   ├── keeper_secrets_manager_helper
│   ├── LICENSE
│   ├── MANIFEST.in
│   ├── README.md
│   ├── requirements.txt
│   ├── setup.py
│   └── tests
├── __init__.py
├── README.md
└── storage
    ├── keeper_secrets_manager_hsm
    ├── keeper_secrets_manager_storage
    ├── LICENSE
    ├── README.md
    ├── requirements.txt
    ├── setup.cfg
    └── setup.py

``` 

The folder `secrets-manager/sdk/python/` is a Python module (it has an `__init__.py`). However the subfolders `core`, `helper`, and `storage` are not importable from the parent module, and they themselves are not modules, but packages, and correspond to what is available in PyPI, for example:

- https://pypi.org/project/keeper-secrets-manager-core/
- https://pypi.org/project/keeper-secrets-manager-helper/
- https://pypi.org/project/keeper-secrets-manager-storage/

To me this is a bit odd, but fine on the surface. However sometime after version 16.4.2 the setup.py files (and requirements.txt) a cyclical dependency was introduced. It became a requirement that `core` could not be installed without `helper`, and `helper` could not be installed without `core`. For dependency resolvers this introduces a deadlock, because package A requires package B, and package B requires package A. Neither package can be installed individually and go through an installation with tests, etc.

My question/suggestion is: Could a good solution be to combine these co-dependent packages as modules under one python SDK package?

**Comment by allanadair** [comment]
@maksimu, could there be any interest in such a change?

**Comment by evilhamsterman** [comment]
I think the point @allanadair is making is that it seems keeper_secrets_manager_helper should just be integrated with core rather than a separate package.

It looks to me like the loop was added when `FieldType` was imported so that someone could add type hints. That's good, you should be using more type hints everywhere, your keepercommander uses the old form of type hints, you should use new type hints here.

But back to the point, everywhere helper is used so is core. Rather than have them be completely separate packages helper could/should just be a module in core. 

Something like this below would let you have the types in helper available everywhere to allow for type hints without a the loop.
```
.
├── LICENSE.txt
├── README.md
├── keeper_secrets_manager_core
│   ├── __init__.py
│   ├── configkeys.py
│   ├── core.py
│   ├── crypto.py
│   ├── dto
│   │   ├── __init__.py
│   │   ├── dtos.py
│   │   └── payload.py
│   ├── exceptions.py
│   ├── helper
│   │   ├── __init__.py
│   │   ├── common.py
│   │   ├── exception.py
│   │   ├── field.py
│   │   ├── field_type.py
│   │   ├── format.py
│   │   ├── record.py
│   │   ├── record_type.py
│   │   ├── tests
│   │   └── v3
│   ├── helpers.py
│   ├── keeper_globals.py
│   ├── mock.py
│   ├── storage.py
│   └── utils.py
├── requirements.txt
├── setup.cfg
├── setup.py
└── tests
    ├── bat_token_test.py
    ├── config_test.py
    ├── core_test.py
    ├── create_records_test.py
    ├── exception_test.py
    ├── mock_test.py
    ├── notation_test.py
    ├── payload_test.py
    ├── record_test.py
    └── smoke_test.py
```

Or separate the fields and record classes/files into a module under core and consolidate your "helper" functions in the `helpers.py` file

**Comment by allanadair** [comment]
Yes @maksimu, removing the "helper" package from the "core" package dependencies does in fact solve the immediate issue. However as @evilhamsterman has also noticed it really sounds like the Python SDK should really be one Python package with submodules for "core", "helper", "storage", etc. I'm not sure how much of an undertaking it would be considering there exists PyPI artifacts and likely some wonderful continuous integration taking place, but it would be nice to see a unified package in the future.

Thanks for all of your hard work!
